print('Olá, eu sou o verificador!')
print('Meu trabalho é lhe dizer tudo sobre o que foi digitado!')
a = input('Digite algo para que eu analize : ')
print(type(a))
print('Numérico? : ', a.isnumeric())
print('Alfanumérico? : ', a.isalnum())
print('Alfabeto? : ', a.isalpha())
print('ASCII? : ', a.isascii())
print('Digito? : ', a.isdigit())
print('Decimal? : ', a.isdecimal())
print('Identificador? : ', a.isidentifier())
print('Letras minúsculas? : ', a.islower())
print('Pode ser Impresso? : ', a.isprintable())
print('Espaço? : ', a.isspace())
print('Título? : ', a.istitle())
print('Maiusculas? : ', a.isupper())
