print('Olá! Bem vindo ao verificador de idade!')
nome = input('Qual é seu nome? : ')
dia = input(nome+', em que dia você nasceu? : ')
print('Ok, anotado!!')
mes = input(nome+', agora me informe o mês de nascimento! : ')
print('Certo!!')
ano = input('Por ultimo '+nome+', agora me informe o ano de nascimento : ')
print ('Processando!!!')
print ('...')
print (nome+', o Dia/Mês/Ano de seu nascimento é : '+dia+'/'+mes+'/'+ano)
