n = int(input('Digite um valor : '))
n1 = float(input('Digite um valor : '))
n2 = bool(input('Digite um valor : '))
n3 = str(input('Digite um valor : '))
n4 = input('Digite algo : ')
print(type(n), n)
print(type(n1), n1)
print(type(n2), n2)
print(type(n3), n3)
print (n4.isnumeric())
